os: linux
dist: trusty
sudo: required
language: ruby

before_install:
- sudo apt-get install -y pandoc rubber
- sudo apt-get install -y texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install -y texlive-latex-recommended texlive-latex-extra
- sudo apt-get install -y texlive-generic-extra texlive-bibtex-extra
- sudo apt-get install -y texlive-science texlive-pictures
- sudo apt-get install -y texlive-xetex

script:
- pdflatex resume.tex
- pdflatex curriculum-vitae.tex
- pdflatex list-of-publications.tex

deploy:
  provider: releases
  api_key:
    secure: RoykAMievvlICCcIVhV3AtawS4YgcgO+HpsUWzfhIJiZF4u4wPE3RUicD2RF08PNO4N3Jglpqf+vtLL8blqqLd2Qf6SZyIwFdUW2ps4hGmhFqnhrE9D12KB5x3ZnVaHvRlvxGuRTh/tzNMHw9qIXmS6cKsdOCPXcOq2X0Vv9zTx1P0w56eW1Z9BvwJfriHJiHSTwJiJtqgWtAiwOHX98lTVsrCcBNWwWCAIXZNdTjmKR753fYFyfTWv2ZczxZ3zUwMQhzlRrz4dFt+1mL1FkCgOtSO/j9+qa5njJyIGfUn4/F4BgRQOSSRF++dZAGDvGW5rtFYx+156jG514ya4xPFcZQXWUDN7ayIVwyuePnIsqVopFQzYz7yQENa0+l6+r4ibitkrFWXpCUtIKkThB2+fIHWECWY3s4XylER+cPbbW3epYta/QBTCiD8llj1ktrRTYMCpdrbGCnRXFBWLh2hMnspwOWLncvcmabVy5+IXU6QaNE70/QxvwFg5lVUdQdOg8yEfwwOiRjDYpYU5uhUnPkSD9XOphLQRvJS6LwqQE+qiMxs4krWHCzdSYKliySUXMgu16xiACcqUBRkclioF7nXilgdl1V63tiB1EFNgxCGn5Rb30LuKIjEo9lEADyImGvietnZHimBIoLfzr7a5MqooSL9eQWEaXkVB7VY0=
  file:
  - resume.pdf
  - curriculum-vitae.pdf
  - list-of-publications.pdf
  skip_cleanup: true
  on:
    repo: wdconinc/cv
